### ISSUE TITLE
Ad 25 Tickets to Ticket List Height

### ISSUE THREAD

**Issue by WhoCares1337** [michaelmaw/spiceworks-hdpp#22]
Spiceworks displays 25 Tickets on each page. It would be useful to be able to choose this as default height of the ticket list too.

**Comment by WhoCares1337** [comment]
Can I add this myself to my spiceworks installation?

**Comment by WhoCares1337** [comment]
I managed to clone the plugin and to fix the issue myself.

**Comment by WhoCares1337** [comment]
I tried to commit the changes I made. Dunno if the upload worked.

**Comment by michaelmaw** [comment]
@WhoCares1337 You would have to submit a pull request for that, but I don't see one. In any case, this looks like a simple update so I'll make sure to add it into the next version. Thanks.

**Comment by WhoCares1337** [comment]
I can't create a pull request. Not sure how this works. But as you say... it's a simple update.
